### ISSUE TITLE
Feature: add option to transfer visible ssids from esp to client

### ISSUE THREAD

**Issue by amandel** [improv-wifi/website#16]
When setting up Wi-Fi credentials you typically select the network name from a drop down or select hidden ssid if the ssid is not visible. 
To allow this to be supported with improv-wifi there needs to be a additional message where the client can request a list of visible ssids from the device (esp).

What do you think?

(Not sure if this is the right place for protocol _Issues_ if not please move it)

**Comment by amandel** [comment]
@balloob  - wrong place or bad topic?

**Comment by TD-er** [comment]
So you mean you let the ESP be the WiFi scanner so you don't need to type in the SSID?

What should be included in the IMPROV reply?
- SSID (or hidden flag)
- BSSID
- RSSI
- Channel
- Encryption

What should be sent back to the ESP? 
- SSID
- WiFi key
- BSSID

**Comment by amandel** [comment]
Thanks for picking this up. 
> So you mean you let the ESP be the WiFi scanner so you don't need to type in the SSID?

Yes!

I would send the minimum needed information from ESP, for me this is 'SSID' and for user experience to display the 'RSSI'. 'Encryption' might be handy for unencrypted networks (no need to ask for the password then). I've to say I do not work with hidden networks at all, I assume a hidden networks need manual input of SSID & password? I might be wrong but neither 'Channel' nor 'BSSID' seem of use here? 

I see no need to add something for the direction -> ESP, this is covered via `RPC Command: Send Wi-Fi settings` already (carrying SSID and password).

**Comment by amandel** [comment]
:) - thanks for adding this. My hope is that such a functionality is added to improv-wifi serial protocol and then to the related implementations. I use improv-wifi serial for the https://github.com/openbikesensor/OpenBikeSensorFirmware project.

It could increase end user experience one more step. (IMHO)

**Comment by TD-er** [comment]
> It could increase end user experience one more step. (IMHO)

Yep, looks like a nice feature to me :)

**Comment by amandel** [comment]
Thanks for bringing this in so silently. Ready to use this with our OpenBikeSensor via https://github.com/esphome/esp-web-tools.
