### ISSUE TITLE
WiFi Demo stuck Provisioning

### ISSUE THREAD

**Issue by ssbrewco** [improv-wifi/website#20]
Having issues getting the WiFi demo on the Improv homepage to work. Here's what we tried:

1. Installed the [ESP Web Tools](https://esphome.github.io/esp-web-tools/) example on an ESP32-PICO-KIT board. Skipped the WiFi setup
2. Disconnected ESP32 from USB/serial port
3. From the Improv homepage, clicked the "Connect device to WiFi" button
4. Successfully paired with device, entered WiFi SSID & password and saved
5. Get a "Provisioning" modal window that spins indefinitely. Same results on MacOS & Win10, both running Chrome 97

Any thoughts would be greatly appreciated!

**Comment by balloob** [comment]
Hm able to reproduce. @jesserockz got an idea what's going on?

![image](https://user-images.githubusercontent.com/1444314/152439717-a0b90565-915d-4e64-9207-e5c8fd4af525.png)

**Comment by jesserockz** [comment]
I see the same. My device connects to Wi-Fi, but does not respond back to the BLE client. I am looking into it

**Comment by balloob** [comment]
We pushed a fix. Can you try the website again

**Comment by ssbrewco** [comment]
Thanks for the very quick fix!

After erasing and re-flashing the ESP32, provisioning a clean device works well.

However, if one attempts to subsequently reconfigure the WiFi credentials after a power cycle, success is elusive. Maybe 1 in 10+ attempts works. In all cases it is possible to pair with the device, but then one of the following errors are seen:

- "An error occurred. No Services matching UUID 00467768-6228-2272-4663-277478268000 found in Device."
- Unknown GATT error
- Infinite Provisioning spin

Reconfiguring WiFi credentials via serial works fine.

**Comment by balloob** [comment]
Wi-Fi credentials are stored and so after a powercycle it will automatically connect to the Wi-Fi. When connected, the BLE server is shut down.

**Comment by ssbrewco** [comment]
Understood that credentials are stored and saved - that seems to be working fine and as expected... thanks for the fix!

The question I had was in regards to _changing_ the stored WiFi credentials after they have been stored. Is there a recommended reliable way to so without erasing & re-flashing?

**Comment by balloob** [comment]
Not currently supported. I suggest you add that to the UI of your own firmware.

**Comment by ssbrewco** [comment]
> Not currently supported. I suggest you add that to the UI of your own firmware.

Noted, thanks for clarifying
