### ISSUE TITLE
Feature request: add command to get IP address from improv device

### ISSUE THREAD

**Issue by Staars** [improv-wifi/website#36]
I would like to pass the IP address of the commissioned device after successful connection to the Improv app (need it for BLE only).

This does not need any code but "only" an addition to the standard (= meaning it is up to the coder to use it or ignore it), like so (using the next free number):

RPC Command: Request IP address

Sends a request for the device to send IP address after successful commissioning. Typically the device will send this without request after commissioning.

Type: 0x03
Command ID: 0x05

This command will trigger one RPC Response containing one string.
Example: 192.168.0.100

**Comment by balloob** [comment]
Why is this needed? You can already return a list of URLs in response to Send Wi-Fi settings (`0x01`). That URL can be a link to the IP.

**Comment by Staars** [comment]
Ahh, you mean this:
This command will generate an RPC result. The first entry in the list is an URL to redirect the user to. If there is no URL, omit the entry or add an empty string.

I missed that somehow.
Thanks 🙏
